version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - kafka-network

  kafka:
    image: confluentinc/cp-kafka:latest
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    networks:
      - kafka-network
    depends_on:
      - zookeeper

  db:
    image: postgres:latest
    networks:
      - kafka-network
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - pgdata:/var/lib/postgresql/data

  main-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
      - kafka
    networks:
      - kafka-network
    ports:
      - "8080:8080"

  client-app:
    build:
      context: .
      dockerfile: CMD/client/Dockerfile
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  pgdata:
